name: Deploy

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          tags: tag:deploy
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Prepare
        run: |
          mv ./target/release/relay-server ${{ secrets.SERVER_DIR }} \
          cd ${{ secrets.SERVER_DIR }}
      - name: Serve
        run: ./relay-server --port 4001 --secret-key-seed 0
