name: Deploy

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: actions/checkout@v4
        run: cargo build --verbose --release